language: go

services:
    - docker

before_deploy:
    - export REPO=$DOCKER_USERNAME/paul-bot
    - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $REPO:$TAG .
deploy:
    provider: script
    script: docker push $REPO
