steps:
    - name: ":golang:"
      commands:
          - "docker build . -t paul-bot:latest"
      plugins:
          - docker#v2.2.0:
              image: "golang:alpine"
              volumes:
                - ".:/go/paul-bot"
                - "/var/run/docker.sock:/var/run/docker.sock"
