steps:
    - name: ":golang:"
      commands:
          - "docker build paul-bot -t paul-bot:latest"
      plugins:
          - docker#v2.2.0:
              image: "docker:latest"
              workdir: /work
              volumes:
                - ".:/work"
                - "/var/run/docker.sock:/var/run/docker.sock"
