# key to authenticate with Discord
# create an application at https://discordapp.com/developers/applications/
# create a bot under the application, and copy the token here
DiscordAPIKey = ""

GoogleAPIKey = ""

# ID of the discord channel you want to send logs to (right click, copy id in
# Discord to find)
LogChannel = ""

# bot's currently "playing" message
StatusMessage = "paul-bot"
